export const UPDATE_STATE = 'UPDATE_STATE';

export const UPDATE_ROUTE_INFO = 'UPDATE_ROUTE_INFO';
export const UPDATE_ROUTE_SHOW = 'UPDATE_ROUTE_SHOW';

export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_SEGMENT = 'UPDATE_SEGMENT';
export const UPDATE_SEGMENT_ID = 'UPDATE_SEGMENT_ID';
export const UPDATE_CONCURRENCIES = 'UPDATE_CONCURRENCIES';
